module.exports = {
    // Sourcemaps are now generated by default and require SASS 3.4.0, gem install sass --pre
    options: {
        style: 'expanded',
        debugInfo: false,
        lineNumbers: false,
        "default-encoding": "UTF-8",
        quiet: true,
        noCache: true,
        precision: 7
    },
    dist: {
        options: {
            lineNumbers: false
        },
        files: [
            {
                '<%= uiPaths.css_dist %>/master.css': '<%= uiPaths.css_src %>/master.scss'
                
            }
        ]
    },
    server: {
        options: {
            lineNumbers: false
        },
        files: [
            {
                '<%= uiPaths.css_dist %>/master.css': '<%= uiPaths.css_src %>/master.scss'                
            }
        ]
    }
};
